servers:
  - host: a.localhost:9000
    proxy_pass: http://127.0.0.1:8000
  - host: b.localhost:9000
    proxy_pass: http://127.0.0.1:8001
  - host: c.localhost:9000
    proxy_pass: http://127.0.0.1:9090
